FROM openjdk:8-jdk-alpine
MAINTAINER rafael.almeida91@hotmail.com
ENV JAR_FILE=target/complains-1.0.0.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]